### ISSUE TITLE
Add: Leave Event Type

### ISSUE THREAD

**Issue by CaliStringer** [CEDStandards/CEDS-Elements#135]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**

Cali Stringer

**Authoring Organization(s)**

CEDS Postsecondary Workgroup, Staff Committee

**Email address**
CStringer@updconsulting.com

**Use Case Title**
Leave Event Type

**Use Case Description** 
The PS workgroup is proposing to add the existing CEDS element, Leave Event Type, to the PS domain. 

Additionally, we propose adding two new elements: leave event start/effective date and a leave event end date. 
Leave Event Type: The option set should match the K-12 Leave Event Type (CEDS 000624). 

Leave Event Start/Effective Date: This element should be added to accompany the Leave Event Type and document the start or effective date of when the leave event began. 

Leave Event End Date: This element should be added to accompany the Leave Event Type and document the date when the leave event ended. 

**Use Case Background**
The leave event will help capture details about PS Staff and the attendance during the school year.  The details of the Leave Event type along with the start and end date will provide the ability for sorting and data analysis. 

**Location of Element in the Domain Entity Schema**
PS | PS Staff |Attendance

**Comment by GeorgePhelps** [comment]
North Carolina would like the new elements listed above (Leave Event Type; Leave Start Date, Leave End Date) also added to 
K12 -> K12 Staff -> Attendance

**Comment by GeorgePhelps** [comment]
Checking to see if any action is taking place to set up meetings towards a proposal for the Start and End Dates.

**Comment by AEMDuaneBrown** [comment]
Questions for the community on this ticket - Currently in the CEDS Integrated Data Store model, the Leave Event Type is modeled in the RoleAttendanceEvent table which couples it with the attendance information. This would mean from that perspective that the Attendance Event Date is used not only to reflect "Present"/"Absent" but also to reflect the Leave Event Type (Annual Leave, Jury Duty, Sick Leave, etc.). So in needing a Leave Event Start Date and Leave Event End Date, we could capture that information with only a single "date" field but that is applied multiple times. If we ignore the topic of attendance briefly, a Leave Event Date as a single element coupled with the Leave Event Type would provide all of the data necessary for determining the range. It could also assist in not applying the date where it would not be applicable. For instance - how many days of annual leave were used by this person with a Leave Event Start Date of July 1st and a Leave Event End Date of July 9th? There are 9 total days so the answer would be 9 - unless we are supposed to remove Holidays and Weekends. If July 5th which was a federal holiday this year is included along with the one weekend, there would be 3 days excluded for the Leave Event Type of Annual Leave making the total only 6 days of annual leave. Using a single date of Leave Event Date we could store the data for each date and apply the Leave Event Type only where it is applicable to the date rather than using a range of dates and needing then to go use calendar information to determine if the person had that day off anyway because it was not a school day in which they should have been present.  So question 1 is - Is one date sufficient for this request rather than a date range?. If the answer to that is yes, then question 2 is - should we keep the Leave Event Type in the RoleAttendanceEvent table coupled with attendance information and use the AttendanceEventDate along with the Leave Event Type? Or should we pull the Leave Event Type out of that location? Naturally, if a staff member is absent from school, the question would be - were they on leave? So there is a coupling here between the data. If a staff member is present on a particular date, they should not have a leave event. If they are absent, then leave could be indicated as part of the reason for the absence. Anyone in the community, feel free to weigh in here.

**Comment by angelajubinvilleqip** [comment]
Proposed Solution for Use Case #135:

The attached document is the proposed solution for this use case and other DES use cases (29 issues, 40 elements). As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: (https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

[Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx](https://github.com/CEDStandards/CEDS-Elements/files/7269661/Add.Elements.to.DES.Issues_149_288_147_146_142_141_140_136_135_123_103_102_101_100_99_96_95_94_93_89_88_87_86_85_76_278_279_280_281.docx)
