### ISSUE TITLE
Add new element Assessment Administered (ELP)

### ISSUE THREAD

**Issue by aemandreahall** [CEDStandards/CEDS-Elements#153]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Andrea Hall

**Authoring Organization(s)**
CEDS/EDFacts

**Email address**
ahall@aemcorp.com

**Use Case Title**
Add a new element to CEDS Assessment Administered (ELP)

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).

**Element Name:**  Alternate Assessment (ELP)
**Definition:** The types of English language proficiency assessments administered.
**Options:** REGELPASMNT - Regular English language proficiency (ELP) assessment; ALTELPASMNTALT: Alternate English language proficiency (ELP) assessment based on alternate ELP achievement standards

**Use Case Background**
Assessment Administered (ELP) is a new EDFacts collection for file specification FS139, Data Group 676 - English language proficiency results.     

**Location of Element in the Domain Entity Schema**
Assessments -> Assessment (or) Assessment -> Assessment Administration

**Comment by jgoodell2** [comment]
This seems like it is and attribute of the Assessment Form (Assessment -> Assessment Form) rather than (Assessment -> Administration) or (Assessments -> Assessment). 
Using Kansas as an example, KS has an Assessment = "KELPA" and the assessments "testing window" is defined by Assessment -> Administration. KELPA might have multiple forms, i.e. separate test instruments for reading, speaking, listening, writing. ...Or reading, speaking, listening, writing are handled within one instrument (Form) as separate Assessment Subtests (e.g. used to score the "reading" parts based on all of the reading items) and Form Section (used for how items are grouped and ordered on a test). An assessment like KELPA could also have separate forms for "Regular English language proficiency" and "Alternate English language proficiency" that would be given during the same testing window to different students. If so the scores would not be comparable since they would be different forms. So...based on what I grasp about this element it best fits in Assessment -> Assessment Form.

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 153

[Add new element Assessment Administered ELP Issue_153.docx](https://github.com/CEDStandards/CEDS-Elements/files/6523003/Add.new.element.Assessment.Administered.ELP.Issue_153.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by AEMDuaneBrown** [comment]
Reopening this ticket. It was not added into version 10.0.0.0. Will add to version 11.0.0.0.
