### ISSUE TITLE
Proposed Addition: Adult Education Certification Type 

### ISSUE THREAD

**Issue by CaliStringer** [CEDStandards/CEDS-Elements#222]
**Author(s)**
Cali Stringer

**Authoring Organization(s)**

CEDS Postsecondary Workgroup, Staff Committee

**Email address**
CStringer@updconsulting.com

**Use Case Title**
Adult Education Certification Type

**Use Case Description** 
We propose adding the existing CEDS element, Adult Education Certification Type, to Postsecondary Staff.

Definition: An indication of the category of certification a person holds.

Option Set: 
AdultEducationCertification - Adult Education Certification
K-12Certification - K-12 Certification
SpecialEducationCertification - Special Education Certification
TESOLCertification - Teachers of English to Speakers of Other Languages (TESOL) Certification
None - None

**Use Case Background**
This element is being suggested to track the types of adult education certifications that a postsecondary staff member may hold. Being able to capture this information will provide details about the qualifications of staff members. 

**Location of Element in the Domain Entity Schema**
Postsecondary Staff

**Comment by jgoodell2** [comment]
Question: Should the definition of this element be "An indication of the category of _**the adult education**_ certification a person holds." (It currently is named "Adult Education Certification Type" but the definition is generic.)

If it applies beyond the AE domain, should it be placed in the generic Credentials domain with a “see also” note in the other applicable domains, rather than being repeated in multiple new places in the Domain Entity Schema?
