### ISSUE TITLE
Add ExitDateFromPostsecondary column in PsStudentEnrollment

### ISSUE THREAD

**Issue by VT-AOE-DMAD-Drew-Bennett** [CEDStandards/CEDS-Elements#286]
**Drew Bennett**

**Agency of Education at the State of Vermont**

drew.bennett@vermont.gov

**ExitDateFromPostsecondary**
In the reference table RefPsEnrollmentStatus, the value for exit date does not exist for enrollment status. Adding this element would impact PsStudentEnrollment.

**Use Case Description**
ExitDateFromPostsecondary —End date for the student’s period of attendance.

**Use Case Background**
Adding ExitDateFromPostsecondary will assist with mapping National Student Clearinghouse enrollment data.

**ExitDateFromPostsecondary**

**Comment by AEMDuaneBrown** [comment]
Follow up for this use case - The PsStudentEnrollment table contains the OrganizationPersonRoleId which would link this record to the Entry and Exit dates related to this PsStudentEnrollment record. The Exit Date in the OrganizationPersonRole table would represent the Enrollment Exit Date. Now there could arise some confusion related to the Enrollment Entry Date since the PsStudentEnrollment table contains an element called EntryDateIntoPostsecondary. What is the difference between Enrollment Entry Date that would appear in OrganizationPersonRole and Entry Date Into Postsecondary? The Entry Date Into Postsecondary was added by stakeholders to fulfill a need identify the first time a student entered into Postsecondary regardless of how many times they enter/exit - what was the first time? That is the Entry Date Into Postsecondary.  So the question for this use case related to ExitDateFromPostsecondary is what is the definition for that element? If it's related to just exiting, then it's possible that Enrollment Exit Date from OrganizationPersonRole could be used. I see the use case is related to National Student Clearinghouse data - curious what their definition is. Is it related to an academic award? Is it related to any and all attendance/exits that occur? If the latter, that seems more aligned with Enrollment Entry Date and Enrollment Exit Date which would be found in the linked OrganizationPersonRole table. But if there is a more specific definition for Exit Date From Postsecondary that can differentiate it from other Enrollment Exit Dates similar to how the Entry Date Into Postsecondary (First time only) is different that all of the other Enrollment Entry Date instances, can you provide more context around that because that would be a use case to add this new element.

**Comment by VT-AOE-DMAD-Drew-Bennett** [comment]
Thanks for getting back to me, Duane! I was confused by the purpose of EntryDateIntoPostSecondary, so thank you for clarifying. I no longer need to add ExitDateFromPostsecondary, since I will load that into OrganizationPersonRole.

**Comment by AEMDuaneBrown** [comment]
Previous comment indicated this ticket is no longer needed - closing.
