### ISSUE TITLE
Need for Elements on Internet/Technology Access at Home

### ISSUE THREAD

**Issue by byoungQIP** [CEDStandards/CEDS-Elements#79]
**Author(s):** Beth Young, CEDS Team

**Use Case Title:** Elements on Internet/Technology Access at Home

**Use Case Description** 
The current use of remote learning has exposed a critical data need in education, the access student’s have to the Internet and digital learning resources at home. Currently, CEDS does not have elements that support this need.

Possible areas of elements needed in CEDS:
1.	Access to Computers at home (by type of computer)
    a.	Shared or dedicated resource
2.	Access to Internet at home (by type of connection)
    a.	Access outside of the house (shared connections)
3.	Use of Computers and Internet at home
   a.	Homework
   b.	Remote learning
   c.	Other

**Use Case Background**
Some existing references-
Kentucky’s Digital and Future Ready Students and Teachers: file:///C:/Users/User/Downloads/Technology%20Readiness%20Survey%20Highlights%20(1).pdf

Student Access to Digital Learning Resources Outside of the Classroom (ACS and CPS):
https://nces.ed.gov/pubs2017/2017098/index.asp 

American Communities Survey (2015):
Had a computer at home:
•	Smart phone
•	Desktop
•	Laptop
•	Netbook
•	Notebook computer
•	Handheld computer/smart phone
•	Some other type of computer

Current Population Survey (2015):
Used the Internet anywhere:
•	Home
•	School
•	Library, Community Center, or other public place
•	Coffee shop or other business that offers Internet access
•	Someone else’s home
•	While traveling between places

Means of Internet access from home:
•	High-speed internet service installed at home
•	Mobile Internet service or data plan
•	Satellite internet service
•	Dial-up service
•	Some other service

Main reason for no Internet access from home:
•	Too expensive
•	Don’t need it
•	No computer
•	Not available in the area
•	Can use it elsewhere
•	Privacy or security concerns
•	Other reasons

**Comment by martinbherbener** [comment]
We do have to be careful about definitions here because there are lots of ways to think about these and the specifics really affect comparability. A couple of considerations around "Means of Internet Access":
- do you specify the technology (fiber, DSL, cell network) or the capabilities/capacity?
- how to represent data caps (amount of data that can transmitted over a month etc.)
- difference between upload and download speeds

Regarding "has a computer at home", it's important to reflect whether the device is individual (the student can use it whenever they need to because no one else uses it) or a shared device by multiple persons in the family.

**Comment by AEMDuaneBrown** [comment]
Ed-Fi has a group of states currently working on elements related to this. Here is the link for reference:
https://techdocs.ed-fi.org/display/EFDSDRAFT/ED-FI+WORKING+DRAFT+3+-+DIGITAL+EQUITY+COLLECTION#ED-FIWORKINGDRAFT3-DIGITALEQUITYCOLLECTION-GeneralDiscussion

**Comment by AEMDuaneBrown** [comment]
CCSSO is coordinating a discussion around these elements with multiple standards organizations and stakeholders. If you are interested in attending, see the announcement and registration link below.

Tuesday, September 1, 2020

2:00 PM EST

CCSSO is inviting stakeholders to participate in a Digital Equity Elements discussion with the purpose of defining a set of standard digital equity elements and option sets.

CCSSO recently released the Home Digital Access Data Collection (https://ccsso.org/sites/default/files/2020-07/7.22.20_CCSSO Home Digital Access Data Collection Blueprint for State Leaders.pdf), a blueprint for state education leaders. In this document, they begin to take a look at data related to digital equity and student home digital access. They call out specifically five elements related to devices and internet access taken from efforts undertaken by the Ed-Fi Alliance, a draft to begin to define out a set of common elements and options. 

The purpose of this discussion will be to start with the five elements, get feedback from the broad stakeholder community and come away with a common definition and set of options. Additionally, we will explore any other needs the stakeholder community sees around this topic which may result in additional collaborative calls and working group sessions. 

The discussion will take place on Tuesday, September 1, 2020 at 2:00 PM EST.  

Register Here (https://aemcorp.adobeconnect.com/e0vwk69mvh55/event/registration.html)

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 79

[Need for Elements on Internet_Technology Access at Home Issue_79.docx](https://github.com/CEDStandards/CEDS-Elements/files/6027250/Need.for.Elements.on.Internet_Technology.Access.at.Home.Issue_79.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by martinbherbener** [comment]
Hello,

- For "Primary Learning Device Provider", option "Personal", the proposed description is "The provider of the primary learning device is the student"; perhaps this could be reworded to "student or guardian" or otherwise indicate that it covers devices that are not literally provided by the student

- For "Internet Access In Residence", we (KY) see value in tracking whether a student has access in other reasonably convenient locations from which they could do schoolwork. To accommodate this, could we change the name to "Internet Access Outside School" and have the option set be something  like "In Residence", "In Other Location", and "Not available" ?

- For "Barrier To Internet Access In Residence" - in KY we have found a small but meaningful number of families that specifically choose not to have Internet at home even though it is available and affordable.  For this reason I suggest another option set item "Not Desired" with Definition "Parent/guardian has chosen not to subscribe to Internet service"

- For "Internet Access Type In Residence" - I am not sure what factors went into the choice of of options. With regards to performance, DSL is significantly worse than other options commonly called Broadband.  "Satellite" has traditionally been fairly poor in performance, but there is potential for low-altitude satellite (Starlink etc.) to be much better, so this category could become misleading.

- For "Internet Access Type In Residence" - some of the Definitions (For Cellular Network through Dialup) appear to be cut off or incomplete; can those be corrected?

- For "Internet Access Type In Residence" - It's not obvious to me what the difference is between "Cellular Network" and "Hotspot", can that be clarified?

thanks!

Martin

**Comment by AEMDuaneBrown** [comment]
Martin,

Thank you for the feedback and the critical eyes on the proposal. I will be resubmitting it shortly. Below is how we are addressing the comments you made.

- For "Primary Learning Device Provider", option "Personal", the proposed description is "The provider of the primary learning device is the student"; perhaps this could be reworded to "student or guardian" or otherwise indicate that it covers devices that are not literally provided by the student
- Comment Response: Great feedback We modified the option description to "student or guardian".
- 
- For "Internet Access In Residence", we (KY) see value in tracking whether a student has access in other reasonably convenient locations from which they could do schoolwork. To accommodate this, could we change the name to "Internet Access Outside School" and have the option set be something like "In Residence", "In Other Location", and "Not available" ?
- Comment Response: Great feedback. In the discussions that occurred, these options came up as well. It was determined that the intent of this particular element was to look at equity. While it was possible for a student to go somewhere else to get internet, what did they normally have available to them in their place of residence. We will leave this element as it is since it has gone through quite a bit of stakeholder vetting, but if you see a need for additional elements around this topic, please feel free to submit a new use case ticket for Internet Access Outside School or any other elements.
- 
- For "Barrier To Internet Access In Residence" - in KY we have found a small but meaningful number of families that specifically choose not to have Internet at home even though it is available and affordable. For this reason I suggest another option set item "Not Desired" with Definition "Parent/guardian has chosen not to subscribe to Internet service"
- Comment Response: I looked back through the notes from the group and an option similar to this was proposed. I will include this option in the updated proposal.
- 
- For "Internet Access Type In Residence" - I am not sure what factors went into the choice of of options. With regards to performance, DSL is significantly worse than other options commonly called Broadband. "Satellite" has traditionally been fairly poor in performance, but there is potential for low-altitude satellite (Starlink etc.) to be much better, so this category could become misleading.
- Comment Response: A lot of discussion went into the options above and changing them at this point would be difficult to do. The main item that came out of the discussions was that "internet speed" itself would be much more valuable information and that these elements provide a quick overview from the parent's perspective of what they have available.  Additional elements have been proposed to capture real-time information for students accessing school assignments through the internet. 
- 
- For "Internet Access Type In Residence" - some of the Definitions (For Cellular Network through Dialup) appear to be cut off or incomplete; can those be corrected?
- Comment Response: Thanks. Good catch. Correcting.
- 
- For "Internet Access Type In Residence" - It's not obvious to me what the difference is between "Cellular Network" and "Hotspot", can that be clarified?
- Comment Response: Agree. Adding additional context in the new proposal. Cellular would refer to a hot spot that can be created with a cellular phone or the use of the phone as the only means to access the internet. A hot spot would refer to a device that is not a cell phone. The cell phone potentially limits the access as it may not be as present or usable as a hot spot which has only one purpose.

**Comment by AEMDuaneBrown** [comment]
Update to Proposed Solution for Issue 79

[Need for Elements on Internet_Technology Access at Home Issue_79_v2.docx](https://github.com/CEDStandards/CEDS-Elements/files/6407136/Need.for.Elements.on.Internet_Technology.Access.at.Home.Issue_79_v2.docx)

**Comment by martinbherbener** [comment]
ok, thanks.
