### ISSUE TITLE
*Add new element: Essential Learning Resource

### ISSUE THREAD

**Issue by jackie-hughes** [CEDStandards/CEDS-Elements#807]
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Jackie Hughes

**Authoring Organization(s)**
AEM Center at CAST
AEM Corp.
Oregon Department of Education
New Hampshire Department of Education
Oklahoma State Department of Education
Nebraska Department of Education
Iowa Department of Education
Bookshare
American Printing House

**Email address**
jhughes@aemcorp.com

**Use Case Title**
*Add new element: Essential Learning Resource

**Use Case Description** 

*Add New Element:** Essential Learning Resource
**Definition: A mandatory learning component integral to the course curriculum, designed to provide fundamental knowledge and skills essential for understanding and completing the course requirements. Its comprehensive nature and relevance make it indispensable for achieving the learning objectives and academic success in the given course.
**Data **Type Object Property****

**DES Location Course>Course Section**

**Use Case Background**
The AEM Center workgroup funded by OSEP proposes the addition of Essential Learning Resource in coordination with Connections built by the group.

**Location of Element in the Domain Entity Schema**
K12>Course Section

**Comment by jackie-hughes** [comment]
[Essential Learning Resource.docx](https://github.com/CEDStandards/CEDS-Elements/files/13532852/Essential.Learning.Resource.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by AEMDuaneBrown** [comment]
Proposed Solution for Issue 807

[Add New Element Essential Learning Resource Issue_807.docx](https://github.com/CEDStandards/CEDS-Elements/files/13547548/Add.New.Element.Essential.Learning.Resource.Issue_807.docx)

The attached document is the proposed solution for this use case. As a community, please review. If no objections exist for the proposed solution, it will be approved as part of the CEDS standard 60 days following the announcement of this proposal as outlined in the OSC Use Case Rubrics/Process (The OSC Use Case Rubrics/Process can be found here: https://github.com/CEDStandards/CEDS-Elements/tree/master/doc).

**Comment by ccurry9825** [comment]
Following up on comments I made during 12/4 OSC meeting: The "Essential Learning Resource" element may prove to be problematic. In today's meeting, I referenced the definition of "print instructional materials" under IDEA and suggested that be considered as a definition for Essential Learning Resource. On reflection, I'd like to retract my comments. "Print instructional materials" under IDEA (including certain digital materials under OSERS 2020 NOI) is specific to materials for which SEAs and LEAs can require publishers to deposit NIMAS file sets to the NIMAC (see Question 9: https://sites.ed.gov/idea/idea-files/questions-and-answers-on-the-national-instructional-materials-accessibility-standard-nimas-aug-9-2021/#_Toc72405089). Because the first set of AEM-related Use Cases and subsequent Connections include a much broader range of Learning Resources and associated accessible formats, I don't think the IDEA definition of print instructional materials is appropriate for "Essential Learning Resource." Furthermore, I believe a legal challenge could be made to any indication that a student with a disability would be denied an educational material issued in a course due to its inaccessibility. Given this concern, I respectfully encourage the OSC to consider omitting this element from CEDS. Thank you.
